### ISSUE TITLE
incompatibility of CDBS grids?

### ISSUE THREAD

**Issue by GailZasowski** [astropy/PyPopStar#3]
Hi,

I've run into an issue with different CDBS files being required when importing popstar and running the examples in the provided notebook.  In particular, the import crashes when pysynphot needs the 'k93models' directory, which is part of the pysynphot libraries currently on STScI's website but not included with the zipped file of models.  The first example in the notebook crashes when pysynphot needs the 'BTSettl_2015_rebin' directory, which is in the zipped file but not in the STScI download.  I can merge them together, and that seems to be working so far, but it seemed odd.

Cheers,
Gail

**Comment by jluastro** [comment]
You should be able to merge them together. The zip file is intended to be unzipped where-ever you have a CDBS directory. Eventually, we hope to add the atmospheres we have generated into CDBS officially; but they don't accept evolution models.
