### ISSUE TITLE
filt_func directory not being copied into the egg file

### ISSUE THREAD

**Issue by GailZasowski** [astropy/PyPopStar#4]
Hi,

Our IT team and I noticed that the filt_func/ directory isn't being copied into the egg file (we were using  popstar-0.0.dev282-py2.7.egg/).  We were able to add it manually and everything seemed to work fine after that.

Cheers,
Gail

**Comment by jluastro** [comment]
Thanks, we will look into fixing that. We probably need to register it somehow in the setup file.

**Comment by jluastro** [comment]
FYI, you can run the whole thing just by adding PopStar/ to your pythonpath as well.

**Comment by GailZasowski** [comment]
Thanks!  Everything runs now (as far as I can tell), this is great!
